//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LakeDrummondWebApp.PhotoGallery._2012_installation_officers {
    
    
    public partial class getthumb {
    }
}
