//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LakeDrummond.PhotoGallery._2009_ddgm_visit {
    
    
    public partial class viewimage {
    }
}
