//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LakeDrummondWebApp.PaymentCenter
{


    public partial class Default
    {

        /// <summary>
        /// Dues control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LakeDrummondWebApp.PaymentCenter.Dues.Dues Dues;

        /// <summary>
        /// FishFry control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LakeDrummondWebApp.PaymentCenter.FishFry.FishFry FishFry;

        /// <summary>
        /// Barbecue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LakeDrummondWebApp.PaymentCenter.Barbecue Barbecue;
    }
}
